// src/lib/appointment-ticket.ts
//
// The printable appointment ticket — what comes out of the printer when the
// front desk checks a client in.
//
// It prints as ONE letter page holding TWO tickets separated by a tear line:
//
//   • STUDIO COPY — stays with the studio or clips to the station. Carries the
//     provider, the station, the booking notes, and a Code 128 barcode so the
//     ticket can be re-scanned later with an ordinary laser wedge scanner.
//   • GUEST STUB — torn off and handed to the client. Carries the confirmation
//     code in large type and a QR that opens their live check-in page, so they
//     can watch their own status, order from the lounge menu, and see what else
//     the studio offers while they wait.
//
// Why both a QR and a barcode: a phone camera reads a QR and cannot read a
// 1D barcode well; a cheap laser wedge scanner reads a 1D barcode and cannot
// read a QR at all. Printing only one guarantees that half the hardware a salon
// might own is useless. Both are generated by @/lib/scan-codes, whose output is
// verified by decoding it, not by looking at it.
//
// Like @/lib/tour-printouts, this file is framework-free and returns a complete,
// self-contained HTML string with inline CSS and no external assets, so it
// prints identically from any browser. It deliberately does NOT rely on the
// app's Tailwind classes: the print window is a blank document that has none of
// them, so anything styled by class name would come out as unstyled text.
//
// v2 adds WALK-IN tickets. A walk-in has no start time and no end time, so the
// time box used to print "Time to be confirmed" — true, but useless to someone
// standing in a lobby. Pass ctx.kind = 'walkin' with a queue position and a
// rough wait and the same page prints their place in line instead. Nothing
// changes for a caller that does not pass ctx.kind.
//
// Two rules that matter more than they look:
//   1. Everything user-provided is HTML-escaped. A client named
//      "A & B <Studio>" cannot break the layout or inject markup.
//   2. internalNotes is NEVER printed. The guest stub is handed to the guest,
//      and the studio copy gets left on counters. Only the booking note the
//      client themselves supplied, and the service note the provider recorded,
//      are safe to put on paper.

import { qrSvg, code128Svg } from '@/lib/scan-codes';
import { openPrintable } from '@/lib/tour-printouts';

/* ── The shapes this file reads ──────────────────────────────────────────── */

/** The fields we read off a tenants/{id}/appointments/{id} document. */
export interface TicketAppointment {
  id?: string | null;
  clientId?: string | null;
  clientName?: string | null;
  serviceId?: string | null;
  addOnIds?: string[] | null;
  staffId?: string | null;
  startTime?: any;
  endTime?: any;
  status?: string | null;
  checkInStatus?: string | null;
  checkInToken?: string | null;
  shortCode?: string | null;
  /** The note the client left when booking. Safe to print. */
  notes?: string | null;
  /** The note the provider recorded at checkout. Safe to print. */
  serviceNotes?: string | null;
  depositAmountCents?: number | null;
  depositStatus?: string | null;
  requiredResourceIds?: string[] | null;
}

/** One lounge order to list on the studio copy. Optional. */
export interface TicketAmenity {
  name?: string | null;
  quantity?: number | null;
  status?: string | null;
}

/**
 * Everything the ticket needs that does NOT live on the appointment document.
 *
 * The appointment stores IDs, not names — there is no serviceName and no price
 * on the document — so the caller resolves them from the collections it already
 * has in memory and passes the display strings in. That keeps this file free of
 * any Firestore dependency and makes it trivially testable.
 */
export interface TicketContext {
  studioName?: string | null;
  studioPhone?: string | null;
  studioEmail?: string | null;
  studioAddress?: string | null;

  clientName?: string | null;
  clientPhone?: string | null;
  serviceName?: string | null;
  addOnNames?: string[] | null;
  staffName?: string | null;
  resourceNames?: string[] | null;

  /** Service price in cents, if the caller wants it on the ticket. */
  priceCents?: number | null;

  /** Lounge orders already placed against this visit. */
  amenities?: TicketAmenity[] | null;

  /**
   * Origin for the guest QR, e.g. "https://studio.example.com". Defaults to the
   * current window's origin, which is correct in the browser and empty during
   * server rendering — in which case the QR falls back to the bare token, which
   * the scanner still understands.
   */
  origin?: string | null;

  /** Extra line in the footer, e.g. a tagline or a cancellation policy. */
  footerNote?: string | null;
  /** The business's brand colour (Studio look accents) and logo. */
  accent?: string | null;
  logoUrl?: string | null;
  /** 'letter' (default: studio copy + guest stub on one page) or 'receipt' (80 mm thermal: the guest stub alone). */
  size?: 'letter' | 'receipt' | null;
  /** Hide the "Powered by ClarityFlow" line. */
  hideBranding?: boolean;

  /**
   * What kind of visit this ticket is for. Omit it (or pass 'appointment') and
   * nothing below changes — every existing caller keeps the exact ticket it has
   * always printed.
   *
   * 'walkin' relabels three things for someone who arrived without a booking:
   * the eyebrow says "Walk-in ticket", the status pill says where they are in
   * the line, and the time box — which for a walk-in has no times in it at all
   * and would otherwise print the rather unhelpful "Time to be confirmed" —
   * carries their place in line and a softened wait instead.
   */
  kind?: 'appointment' | 'walkin' | null;

  /** 1-based place in the walk-in line. Ignored unless kind is 'walkin'. */
  queuePosition?: number | null;

  /**
   * Rough wait in minutes. Printed as "About 25 minutes", never as a countdown:
   * paper cannot tick down, and a guest holding a stub that promised 12 minutes
   * twenty minutes ago is a guest at the desk asking why.
   */
  queueWaitMinutes?: number | null;

  /** Overrides the wait sentence entirely, e.g. "Maya is ready for you now". */
  queueNote?: string | null;
}

/* ── Small helpers ───────────────────────────────────────────────────────── */

const esc = (v: any): string =>
  String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

/**
 * Every date on an appointment has arrived from at least three places over the
 * life of this app: an ISO string, a Firestore Timestamp, and a real Date. Any
 * of them can also be null on an older document. This returns null rather than
 * an Invalid Date so that every caller below has to decide what to show, which
 * is the only way to be sure a half-filled appointment prints a dash instead of
 * the string "Invalid Date" on a ticket handed to a paying client.
 */
function toDate(value: any): Date | null {
  if (!value) return null;
  if (value instanceof Date) return isNaN(value.getTime()) ? null : value;
  if (typeof value === 'object' && typeof value.toDate === 'function') {
    try {
      const d = value.toDate();
      return d instanceof Date && !isNaN(d.getTime()) ? d : null;
    } catch {
      return null;
    }
  }
  if (typeof value === 'object' && typeof value.seconds === 'number') {
    const d = new Date(value.seconds * 1000);
    return isNaN(d.getTime()) ? null : d;
  }
  const d = new Date(value);
  return isNaN(d.getTime()) ? null : d;
}

const fmt = (d: Date | null, opts: Intl.DateTimeFormatOptions): string => {
  if (!d) return '';
  try {
    return d.toLocaleString('en-US', opts);
  } catch {
    return '';
  }
};

const dayLabel = (d: Date | null) =>
  fmt(d, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
const timeLabel = (d: Date | null) => fmt(d, { hour: 'numeric', minute: '2-digit' });

const money = (cents?: number | null): string => {
  const n = Number(cents);
  if (!Number.isFinite(n) || n <= 0) return '';
  try {
    return (n / 100).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
  } catch {
    return `$${(n / 100).toFixed(2)}`;
  }
};

const titleCase = (v: any): string =>
  String(v ?? '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (m) => m.toUpperCase())
    .trim();

const minutesBetween = (a: Date | null, b: Date | null): number => {
  if (!a || !b) return 0;
  const mins = Math.round((b.getTime() - a.getTime()) / 60000);
  return mins > 0 ? mins : 0;
};

const durationLabel = (mins: number): string => {
  if (mins <= 0) return '';
  if (mins < 60) return `${mins} min`;
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return m ? `${h} hr ${m} min` : `${h} hr`;
};

/* ── What gets scanned ───────────────────────────────────────────────────── */

/**
 * Resolves the one value that both codes on this ticket will carry.
 *
 * The short code is preferred because it is short enough to read aloud over the
 * phone and to type by hand. When an older appointment has no short code we
 * fall back to the full check-in token, which the scanner also understands —
 * NOT to a truncated version of it, because a truncated token matches nothing
 * and would print a code that fails silently in the client's hand.
 */
export function ticketScanValue(apt: TicketAppointment): { value: string; isShortCode: boolean } {
  const code = String(apt.shortCode ?? '').trim();
  if (code) return { value: code, isShortCode: true };
  const token = String(apt.checkInToken ?? '').trim();
  return { value: token, isShortCode: false };
}

/**
 * The URL the guest's QR opens. Short codes are case-insensitive on lookup, but
 * check-in tokens are not, so the token is never case-folded.
 */
export function ticketCheckInUrl(apt: TicketAppointment, origin?: string | null): string {
  const token = String(apt.checkInToken ?? '').trim();
  if (!token) return '';
  const base = String(
    origin ?? (typeof window !== 'undefined' ? window.location.origin : '')
  ).replace(/\/+$/, '');
  return base ? `${base}/check-in/${token}` : '';
}

/* ── Markup fragments ────────────────────────────────────────────────────── */

function field(label: string, value: any): string {
  const v = String(value ?? '').trim();
  if (!v) return '';
  return `<div class="f"><div class="k">${esc(label)}</div><div class="v">${esc(v)}</div></div>`;
}

function pills(items: (string | null | undefined)[]): string {
  const list = items.map((s) => String(s ?? '').trim()).filter(Boolean);
  if (!list.length) return '';
  return list.map((s) => `<span class="pill">${esc(s)}</span>`).join('');
}

/**
 * The code block. Falls back to plain monospace text when a code cannot be
 * encoded, so a ticket is still usable rather than showing a blank gap — both
 * qrSvg and code128Svg return an empty string instead of emitting a symbol they
 * cannot encode correctly.
 */
function codeBlock(svg: string, human: string, caption: string, note: string): string {
  const art = svg
    ? `<div class="art">${svg}</div>`
    : `<div class="art art-empty"><span class="mono-big">${esc(human || '—')}</span></div>`;
  return `
    <div class="code">
      ${art}
      <div class="code-txt">
        <div class="k">${esc(caption)}</div>
        ${human ? `<div class="mono">${esc(human)}</div>` : ''}
        <div class="hint">${esc(note)}</div>
      </div>
    </div>`;
}

/* ── The document ────────────────────────────────────────────────────────── */

/**
 * Builds the complete printable ticket for one appointment.
 *
 * Returns an HTML document string. Nothing is written to the DOM and no window
 * is opened — pass the result to printAppointmentTicket() or to openPrintable()
 * from @/lib/tour-printouts.
 */
export function appointmentTicketHtml(apt: TicketAppointment, ctx: TicketContext = {}): string {
  const studioName = String(ctx.studioName ?? '').trim() || 'Studio';
  const accent = /^#[0-9a-fA-F]{3,8}$|^(rgb|hsl)a?\([^)]*\)$/.test(String(ctx.accent || '').trim()) ? String(ctx.accent).trim() : '#1c1917';   // only a real colour reaches the CSS
  const logo = /^https:\/\//.test(String(ctx.logoUrl || '')) ? String(ctx.logoUrl) : '';
  const receipt = ctx.size === 'receipt';
  const clientName =
    String(ctx.clientName ?? '').trim() || String(apt.clientName ?? '').trim() || 'Guest';
  const serviceName = String(ctx.serviceName ?? '').trim() || 'Appointment';
  const staffName = String(ctx.staffName ?? '').trim();

  const start = toDate(apt.startTime);
  const end = toDate(apt.endTime);
  const day = dayLabel(start);
  const from = timeLabel(start);
  const to = timeLabel(end);
  const window_ = from ? (to ? `${from} – ${to}` : from) : '';
  const duration = durationLabel(minutesBetween(start, end));

  const { value: scanValue, isShortCode } = ticketScanValue(apt);
  // Short codes are matched case-insensitively at lookup, so printing them
  // uppercase is both safe and far easier to read off paper. Tokens are matched
  // exactly and must be left alone.
  const codeForScanner = isShortCode ? scanValue.toUpperCase() : scanValue;
  const codeForHumans = isShortCode ? scanValue.toUpperCase() : '';

  const checkInUrl = ticketCheckInUrl(apt, ctx.origin);
  // Whatever the guest scans has to resolve. A full URL opens their page in one
  // tap; with no origin available the bare token still identifies the visit.
  const qrPayload = checkInUrl || String(apt.checkInToken ?? '').trim() || codeForScanner;

  const qr = qrPayload ? qrSvg(qrPayload, 118) : '';
  const barcode = codeForScanner ? code128Svg(codeForScanner, 46, 2) : '';

  const addOns = (ctx.addOnNames ?? []).map((s) => String(s ?? '').trim()).filter(Boolean);
  const stations = (ctx.resourceNames ?? []).map((s) => String(s ?? '').trim()).filter(Boolean);
  const price = money(ctx.priceCents);
  const deposit = money(apt.depositAmountCents);
  const depositLine = deposit
    ? `${deposit}${apt.depositStatus ? ` · ${titleCase(apt.depositStatus)}` : ''}`
    : '';

  const bookingNote = String(apt.notes ?? '').trim();
  const serviceNote = String(apt.serviceNotes ?? '').trim();

  const amenities = (ctx.amenities ?? [])
    .map((a) => {
      const name = String(a?.name ?? '').trim();
      if (!name) return '';
      const qty = Number(a?.quantity);
      const q = Number.isFinite(qty) && qty > 1 ? ` ×${qty}` : '';
      const st = String(a?.status ?? '').trim();
      return `<li><span>${esc(name)}${esc(q)}</span>${st ? `<span class="tag">${esc(titleCase(st))}</span>` : ''}</li>`;
    })
    .filter(Boolean)
    .join('');

  // ── Walk-in framing ──────────────────────────────────────────────────────
  // All of this collapses to empty strings for a normal appointment, so the
  // markup below is unchanged for every existing caller.
  const isWalkIn = String(ctx.kind ?? '') === 'walkin';
  const posNum = Number(ctx.queuePosition);
  const queuePos = Number.isFinite(posNum) && posNum > 0 ? Math.round(posNum) : 0;
  const waitNum = Number(ctx.queueWaitMinutes);
  const waitMins = Number.isFinite(waitNum) && waitNum > 0 ? Math.round(waitNum) : 0;
  const queueLine = !isWalkIn
    ? ''
    : String(ctx.queueNote ?? '').trim() ||
      (waitMins ? `About ${waitMins} minutes` : 'We will come get you shortly');
  const eyebrowLabel = isWalkIn ? 'Walk-in ticket' : 'Appointment ticket';
  const posLabel = queuePos ? `#${queuePos} in line` : 'In line';

  const statusLabel = isWalkIn
    ? (queuePos ? `In line · #${queuePos}` : 'In line')
    : titleCase(apt.checkInStatus === 'arrived' ? 'checked in' : apt.status) || 'Confirmed';

  // Printed on the guest stub, which is the half that leaves the building: the
  // address is there so someone holding the stub knows where to come back to,
  // and the phone so they can call without hunting for the number.
  const contactBits = [ctx.studioPhone, ctx.studioEmail, ctx.studioAddress]
    .map((s) => String(s ?? '').trim())
    .filter(Boolean)
    .map(esc)
    .join(' · ');

  const footBits = [
    esc(studioName),
    ctx.footerNote ? esc(String(ctx.footerNote).trim()) : '',
    `Printed ${esc(fmt(new Date(), { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }))}`,
    ctx.hideBranding ? '' : 'Powered by ClarityFlow',
  ]
    .filter(Boolean)
    .join(' · ');

  return `<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" />
<title>${esc(`Ticket · ${clientName}`)}</title>
<style>
  /* THE STUDIO LOOK — warm paper, Plus Jakarta Sans, soft rounded cards, the business's own colour.
     The QR and the barcode are never tinted or resized: that's what keeps them scanning. */
  :root { --ink:#1c1917; --muted:#57534e; --soft:#a8a29e; --line:#e7e2dc; --wash:#f1ece6; --paper:#faf8f5; --accent:${accent}; }
  * { box-sizing:border-box; }
  html, body { margin:0; padding:0; background:var(--paper); color:var(--ink);
    font-family:"Plus Jakarta Sans",system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    -webkit-print-color-adjust:exact; print-color-adjust:exact; }
  .toolbar { position:sticky; top:0; z-index:5; display:flex; gap:8px; justify-content:center; padding:14px;
    background:rgba(250,248,245,.92); backdrop-filter:blur(8px); border-bottom:1px solid var(--line); }
  .toolbar button { font:inherit; font-weight:600; font-size:14px; color:#fff; background:var(--accent); border:0; border-radius:999px;
    padding:0 22px; min-height:44px; cursor:pointer; }
  .toolbar button.secondary { background:#fff; color:var(--ink); border:1px solid var(--line); }

  .sheet { max-width:720px; margin:24px auto; }
  .ticket { background:#fff; border:1px solid var(--line); border-radius:28px; overflow:hidden; box-shadow:0 18px 50px -24px rgba(28,25,23,.25); }

  .band { display:flex; align-items:center; justify-content:space-between; gap:12px; padding:16px 24px;
    background:color-mix(in srgb, var(--accent) 9%, #fff); border-bottom:1px solid var(--line); }
  .band .who { display:flex; align-items:center; gap:10px; font-size:15px; font-weight:700; letter-spacing:-.01em; min-width:0; flex:1 1 auto; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
  .band .who img { max-height:30px; max-width:140px; object-fit:contain; }
  .band .st { font-size:12px; font-weight:600; color:var(--accent); background:#fff; border:1px solid color-mix(in srgb, var(--accent) 30%, var(--line));
    border-radius:999px; padding:5px 12px; white-space:nowrap; }

  .body { padding:24px 26px 26px; }
  .eyebrow { font-size:11px; font-weight:600; letter-spacing:.14em; text-transform:uppercase; color:var(--muted); margin:0 0 6px; }
  h1 { font-size:30px; line-height:1.08; letter-spacing:-.025em; margin:0 0 4px; font-weight:700; }
  .svc { font-size:16px; font-weight:500; color:var(--muted); margin:0; }

  .when { display:flex; flex-wrap:wrap; align-items:baseline; gap:6px 14px; background:var(--wash); border-radius:18px; padding:14px 18px; margin:20px 0 4px; }
  .when .d { font-size:14px; font-weight:600; color:var(--muted); width:100%; }
  .when .t { font-size:26px; font-weight:700; letter-spacing:-.02em; white-space:nowrap; }
  .when .dur { font-size:12px; font-weight:600; color:var(--muted); }

  .fields { display:grid; grid-template-columns:1fr 1fr; gap:0 26px; margin:14px 0 0; }
  .f { border-bottom:1px solid var(--line); padding:10px 0; min-width:0; }
  .k { font-size:11px; font-weight:600; letter-spacing:.08em; text-transform:uppercase; color:var(--soft); }
  .v { font-size:15px; font-weight:600; margin-top:2px; overflow-wrap:break-word; }

  h2 { font-size:12px; font-weight:700; letter-spacing:.1em; text-transform:uppercase; color:var(--accent); margin:22px 0 8px; }
  .pill { display:inline-block; background:var(--wash); border-radius:999px; padding:5px 12px; font-size:12px; font-weight:600; margin:0 6px 6px 0; }
  .note { background:var(--paper); border:1px solid var(--line); border-left:3px solid var(--accent); border-radius:14px; padding:11px 13px;
    font-size:13px; line-height:1.5; color:var(--muted); white-space:pre-wrap; overflow-wrap:break-word; }
  ul.amen { list-style:none; margin:0; padding:0; }
  ul.amen li { display:flex; align-items:center; justify-content:space-between; gap:10px; border-bottom:1px solid var(--line); padding:7px 0; font-size:13px; font-weight:600; }
  .tag { font-size:11px; font-weight:600; color:var(--muted); background:var(--wash); border-radius:999px; padding:3px 9px; white-space:nowrap; }

  .code { display:flex; align-items:center; gap:16px; margin-top:10px; }
  .art { flex:0 0 auto; line-height:0; background:#fff; }
  .art svg { display:block; }
  .art-empty { line-height:1.2; }
  .code-txt { min-width:0; }
  .mono { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:17px; font-weight:700; letter-spacing:.16em; margin-top:3px; overflow-wrap:break-word; }
  .mono-big { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:22px; font-weight:700; letter-spacing:.14em; }
  .hint { font-size:12px; color:var(--muted); margin-top:4px; line-height:1.45; }

  .tear { display:flex; align-items:center; gap:10px; margin:0 0 10px; padding:0 6px; color:var(--soft); font-size:11px; font-weight:600;
    letter-spacing:.12em; line-height:1.6; text-transform:uppercase; }
  .tear .ln { flex:1 1 auto; border-top:2px dashed var(--line); }
  .stub-wrap { margin-top:18px; }

  .stub { background:#fff; border:2px dashed color-mix(in srgb, var(--accent) 35%, var(--line)); border-radius:24px; padding:20px 22px; display:flex; gap:20px; align-items:center; }
  .stub .left { flex:1 1 auto; min-width:0; }
  .stub .right { flex:0 0 auto; text-align:center; }
  .stub h3 { font-size:22px; letter-spacing:-.02em; margin:2px 0 2px; font-weight:700; }
  .stub .meta { font-size:13px; color:var(--muted); font-weight:500; }
  .stub .big-code { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:28px; font-weight:700; letter-spacing:.24em; margin:10px 0 2px; color:var(--ink); }
  .stub .url { font-size:11px; color:var(--soft); overflow-wrap:break-word; }

  .foot { margin:14px 4px 0; font-size:11px; color:var(--soft); text-align:center; }

  @media (max-width:560px) {
    .sheet { margin:14px 12px; } .body { padding:20px 18px 22px; } h1 { font-size:25px; } .fields { grid-template-columns:1fr; }
    .code { flex-direction:column; align-items:flex-start; } .stub { flex-direction:column; align-items:flex-start; } .stub .right { text-align:left; }
  }
  /* RECEIPT PRINTER (80 mm): the guest stub on its own, one narrow column, no tints (thermal paper is black on white). */
  body.receipt .sheet { max-width:300px; margin:12px auto; }
  body.receipt .ticket, body.receipt .tear { display:none; }
  body.receipt .stub-wrap { margin:0; }
  body.receipt .stub { flex-direction:column; align-items:center; text-align:center; border-radius:18px; padding:16px 14px; gap:10px; }
  body.receipt .stub .right { text-align:center; }
  body.receipt .band-mini { display:flex !important; }
  body.receipt .stub .eyebrow { display:none; }   /* the business name is already at the top */

  @media print {
    body { background:#fff; } .toolbar { display:none; }
    .sheet { max-width:none; margin:0; }
    .ticket { box-shadow:none; border-radius:20px; break-inside:avoid; page-break-inside:avoid; }
    .stub { break-inside:avoid; page-break-inside:avoid; padding:15px 18px; }
    .stub-wrap { margin-top:8px; } .tear { margin:0 0 7px; }
    .band { padding:11px 20px; } .body { padding:16px 20px 18px; } h1 { font-size:26px; } h2 { margin:13px 0 6px; }
    .when { padding:11px 15px; margin:13px 0 0; } .fields { margin-top:8px; } .f { padding:6px 0; } .note { padding:9px 12px; }
    ul.amen li { padding:4px 0; } .code { margin-top:6px; } .foot { margin-top:8px; }
    @page { margin:0.45in; }
    body.receipt .sheet { max-width:none; width:72mm; margin:0 auto; }
    body.receipt .stub { border:0; border-radius:0; padding:2mm 0; }
    body.receipt .band-mini { background:none !important; }
  }
  @page receipt { size:80mm auto; margin:3mm; }
  body.receipt { page:receipt; }
  .band-mini { display:none; flex-direction:column; align-items:center; gap:6px; margin-bottom:6px; font-size:14px; font-weight:700; }
  .band-mini img { max-height:34px; max-width:180px; object-fit:contain; }
</style></head>
<body class="${receipt ? 'receipt' : ''}">
  <div class="toolbar">
    <button onclick="window.print()">Print ticket</button>
    <button class="secondary" onclick="window.close()">Close</button>
  </div>

  <div class="sheet">
    <div class="ticket">
      <div class="band">
        <div class="who">${logo ? `<img src="${esc(logo)}" alt="" />` : ''}<span>${esc(studioName)}</span></div>
        <div class="st">${esc(statusLabel)}</div>
      </div>
      <div class="body">
        <p class="eyebrow">${esc(eyebrowLabel)}</p>
        <h1>${esc(clientName)}</h1>
        <p class="svc">${esc(serviceName)}</p>

        <div class="when">
          ${day ? `<div class="d">${esc(day)}</div>` : ''}
          ${
            window_
              ? `<div class="t">${esc(window_)}</div>`
              : isWalkIn
                ? `<div class="t">${esc(posLabel)}</div>`
                : '<div class="t">Time to be confirmed</div>'
          }
          ${
            duration
              ? `<div class="dur">${esc(duration)}</div>`
              : queueLine
                ? `<div class="dur">${esc(queueLine)}</div>`
                : ''
          }
        </div>

        <div class="fields">
          ${field('Provider', staffName)}
          ${field(stations.length > 1 ? 'Stations' : 'Station', stations.join(' · '))}
          ${field('Service total', price)}
          ${field('Deposit', depositLine)}
          ${field('Contact', ctx.clientPhone)}
          ${field('Confirmation', codeForHumans)}
        </div>

        ${addOns.length ? `<h2>Add-ons</h2><div>${pills(addOns)}</div>` : ''}
        ${bookingNote ? `<h2>Client request</h2><p class="note">${esc(bookingNote)}</p>` : ''}
        ${serviceNote ? `<h2>Service note</h2><p class="note">${esc(serviceNote)}</p>` : ''}
        ${amenities ? `<h2>Lounge orders</h2><ul class="amen">${amenities}</ul>` : ''}

        <h2>Scan to pull this ticket up</h2>
        ${codeBlock(
          barcode,
          codeForHumans,
          'Studio scanner',
          'Scan with the desk scanner to open this appointment, or type the code into the planner search.'
        )}
      </div>
    </div>

    <div class="stub-wrap">
      <div class="tear"><span class="ln"></span> Tear here · guest copy <span class="ln"></span></div>
      <div class="stub">
        <div class="band-mini">${logo ? `<img src="${esc(logo)}" alt="" />` : ''}<span>${esc(studioName)}</span></div>
        <div class="left">
          <p class="eyebrow">${esc(studioName)}</p>
          <h3>${esc(clientName)}</h3>
          <div class="meta">${esc(
            (isWalkIn
              ? [serviceName, posLabel, queueLine]
              : [serviceName, day, window_]
            ).filter(Boolean).join(' · '),
          )}</div>
          ${codeForHumans ? `<div class="big-code">${esc(codeForHumans)}</div>` : ''}
          <div class="url">${
            checkInUrl
              ? `Scan the code to follow your visit, order from the lounge, and see what else we offer.<br />${esc(checkInUrl)}`
              : 'Keep this stub — the front desk can look your visit up with this code.'
          }</div>
          ${contactBits ? `<div class="url" style="margin-top:6px;">${contactBits}</div>` : ''}
        </div>
        ${qr ? `<div class="right"><div class="art">${qr}</div></div>` : ''}
      </div>
    </div>

    <div class="foot">${footBits}</div>
  </div>
  <script>try{window.focus();}catch(e){}</script>
</body></html>`;
}

/**
 * Builds the ticket and opens it in a new tab with the print dialog ready.
 *
 * Returns false when a popup blocker stopped the window from opening, which is
 * common and silent — the caller should surface a toast telling the owner to
 * allow popups, otherwise pressing Print appears to do nothing at all.
 */
export function printAppointmentTicket(apt: TicketAppointment, ctx: TicketContext = {}): boolean {
  return openPrintable(appointmentTicketHtml(apt, ctx));
}
