// src/lib/appointment-ticket.ts
//
// The printable appointment ticket — what comes out of the printer when the
// front desk checks a client in.
//
// It prints as ONE letter page holding TWO tickets separated by a tear line:
//
//   • STUDIO COPY — stays with the studio or clips to the station. Carries the
//     provider, the station, the booking notes, and a Code 128 barcode so the
//     ticket can be re-scanned later with an ordinary laser wedge scanner.
//   • GUEST STUB — torn off and handed to the client. Carries the confirmation
//     code in large type and a QR that opens their live check-in page, so they
//     can watch their own status, order from the lounge menu, and see what else
//     the studio offers while they wait.
//
// Why both a QR and a barcode: a phone camera reads a QR and cannot read a
// 1D barcode well; a cheap laser wedge scanner reads a 1D barcode and cannot
// read a QR at all. Printing only one guarantees that half the hardware a salon
// might own is useless. Both are generated by @/lib/scan-codes, whose output is
// verified by decoding it, not by looking at it.
//
// Like @/lib/tour-printouts, this file is framework-free and returns a complete,
// self-contained HTML string with inline CSS and no external assets, so it
// prints identically from any browser. It deliberately does NOT rely on the
// app's Tailwind classes: the print window is a blank document that has none of
// them, so anything styled by class name would come out as unstyled text.
//
// Two rules that matter more than they look:
//   1. Everything user-provided is HTML-escaped. A client named
//      "A & B <Studio>" cannot break the layout or inject markup.
//   2. internalNotes is NEVER printed. The guest stub is handed to the guest,
//      and the studio copy gets left on counters. Only the booking note the
//      client themselves supplied, and the service note the provider recorded,
//      are safe to put on paper.

import { qrSvg, code128Svg } from '@/lib/scan-codes';
import { openPrintable } from '@/lib/tour-printouts';

/* ── The shapes this file reads ──────────────────────────────────────────── */

/** The fields we read off a tenants/{id}/appointments/{id} document. */
export interface TicketAppointment {
  id?: string | null;
  clientId?: string | null;
  clientName?: string | null;
  serviceId?: string | null;
  addOnIds?: string[] | null;
  staffId?: string | null;
  startTime?: any;
  endTime?: any;
  status?: string | null;
  checkInStatus?: string | null;
  checkInToken?: string | null;
  shortCode?: string | null;
  /** The note the client left when booking. Safe to print. */
  notes?: string | null;
  /** The note the provider recorded at checkout. Safe to print. */
  serviceNotes?: string | null;
  depositAmountCents?: number | null;
  depositStatus?: string | null;
  requiredResourceIds?: string[] | null;
}

/** One lounge order to list on the studio copy. Optional. */
export interface TicketAmenity {
  name?: string | null;
  quantity?: number | null;
  status?: string | null;
}

/**
 * Everything the ticket needs that does NOT live on the appointment document.
 *
 * The appointment stores IDs, not names — there is no serviceName and no price
 * on the document — so the caller resolves them from the collections it already
 * has in memory and passes the display strings in. That keeps this file free of
 * any Firestore dependency and makes it trivially testable.
 */
export interface TicketContext {
  studioName?: string | null;
  studioPhone?: string | null;
  studioEmail?: string | null;
  studioAddress?: string | null;

  clientName?: string | null;
  clientPhone?: string | null;
  serviceName?: string | null;
  addOnNames?: string[] | null;
  staffName?: string | null;
  resourceNames?: string[] | null;

  /** Service price in cents, if the caller wants it on the ticket. */
  priceCents?: number | null;

  /** Lounge orders already placed against this visit. */
  amenities?: TicketAmenity[] | null;

  /**
   * Origin for the guest QR, e.g. "https://studio.example.com". Defaults to the
   * current window's origin, which is correct in the browser and empty during
   * server rendering — in which case the QR falls back to the bare token, which
   * the scanner still understands.
   */
  origin?: string | null;

  /** Extra line in the footer, e.g. a tagline or a cancellation policy. */
  footerNote?: string | null;
  /** Hide the "Powered by ClarityFlow" line. */
  hideBranding?: boolean;
}

/* ── Small helpers ───────────────────────────────────────────────────────── */

const esc = (v: any): string =>
  String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

/**
 * Every date on an appointment has arrived from at least three places over the
 * life of this app: an ISO string, a Firestore Timestamp, and a real Date. Any
 * of them can also be null on an older document. This returns null rather than
 * an Invalid Date so that every caller below has to decide what to show, which
 * is the only way to be sure a half-filled appointment prints a dash instead of
 * the string "Invalid Date" on a ticket handed to a paying client.
 */
function toDate(value: any): Date | null {
  if (!value) return null;
  if (value instanceof Date) return isNaN(value.getTime()) ? null : value;
  if (typeof value === 'object' && typeof value.toDate === 'function') {
    try {
      const d = value.toDate();
      return d instanceof Date && !isNaN(d.getTime()) ? d : null;
    } catch {
      return null;
    }
  }
  if (typeof value === 'object' && typeof value.seconds === 'number') {
    const d = new Date(value.seconds * 1000);
    return isNaN(d.getTime()) ? null : d;
  }
  const d = new Date(value);
  return isNaN(d.getTime()) ? null : d;
}

const fmt = (d: Date | null, opts: Intl.DateTimeFormatOptions): string => {
  if (!d) return '';
  try {
    return d.toLocaleString('en-US', opts);
  } catch {
    return '';
  }
};

const dayLabel = (d: Date | null) =>
  fmt(d, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
const timeLabel = (d: Date | null) => fmt(d, { hour: 'numeric', minute: '2-digit' });

const money = (cents?: number | null): string => {
  const n = Number(cents);
  if (!Number.isFinite(n) || n <= 0) return '';
  try {
    return (n / 100).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
  } catch {
    return `$${(n / 100).toFixed(2)}`;
  }
};

const titleCase = (v: any): string =>
  String(v ?? '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (m) => m.toUpperCase())
    .trim();

const minutesBetween = (a: Date | null, b: Date | null): number => {
  if (!a || !b) return 0;
  const mins = Math.round((b.getTime() - a.getTime()) / 60000);
  return mins > 0 ? mins : 0;
};

const durationLabel = (mins: number): string => {
  if (mins <= 0) return '';
  if (mins < 60) return `${mins} min`;
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return m ? `${h} hr ${m} min` : `${h} hr`;
};

/* ── What gets scanned ───────────────────────────────────────────────────── */

/**
 * Resolves the one value that both codes on this ticket will carry.
 *
 * The short code is preferred because it is short enough to read aloud over the
 * phone and to type by hand. When an older appointment has no short code we
 * fall back to the full check-in token, which the scanner also understands —
 * NOT to a truncated version of it, because a truncated token matches nothing
 * and would print a code that fails silently in the client's hand.
 */
export function ticketScanValue(apt: TicketAppointment): { value: string; isShortCode: boolean } {
  const code = String(apt.shortCode ?? '').trim();
  if (code) return { value: code, isShortCode: true };
  const token = String(apt.checkInToken ?? '').trim();
  return { value: token, isShortCode: false };
}

/**
 * The URL the guest's QR opens. Short codes are case-insensitive on lookup, but
 * check-in tokens are not, so the token is never case-folded.
 */
export function ticketCheckInUrl(apt: TicketAppointment, origin?: string | null): string {
  const token = String(apt.checkInToken ?? '').trim();
  if (!token) return '';
  const base = String(
    origin ?? (typeof window !== 'undefined' ? window.location.origin : '')
  ).replace(/\/+$/, '');
  return base ? `${base}/check-in/${token}` : '';
}

/* ── Markup fragments ────────────────────────────────────────────────────── */

function field(label: string, value: any): string {
  const v = String(value ?? '').trim();
  if (!v) return '';
  return `<div class="f"><div class="k">${esc(label)}</div><div class="v">${esc(v)}</div></div>`;
}

function pills(items: (string | null | undefined)[]): string {
  const list = items.map((s) => String(s ?? '').trim()).filter(Boolean);
  if (!list.length) return '';
  return list.map((s) => `<span class="pill">${esc(s)}</span>`).join('');
}

/**
 * The code block. Falls back to plain monospace text when a code cannot be
 * encoded, so a ticket is still usable rather than showing a blank gap — both
 * qrSvg and code128Svg return an empty string instead of emitting a symbol they
 * cannot encode correctly.
 */
function codeBlock(svg: string, human: string, caption: string, note: string): string {
  const art = svg
    ? `<div class="art">${svg}</div>`
    : `<div class="art art-empty"><span class="mono-big">${esc(human || '—')}</span></div>`;
  return `
    <div class="code">
      ${art}
      <div class="code-txt">
        <div class="k">${esc(caption)}</div>
        ${human ? `<div class="mono">${esc(human)}</div>` : ''}
        <div class="hint">${esc(note)}</div>
      </div>
    </div>`;
}

/* ── The document ────────────────────────────────────────────────────────── */

/**
 * Builds the complete printable ticket for one appointment.
 *
 * Returns an HTML document string. Nothing is written to the DOM and no window
 * is opened — pass the result to printAppointmentTicket() or to openPrintable()
 * from @/lib/tour-printouts.
 */
export function appointmentTicketHtml(apt: TicketAppointment, ctx: TicketContext = {}): string {
  const studioName = String(ctx.studioName ?? '').trim() || 'Studio';
  const clientName =
    String(ctx.clientName ?? '').trim() || String(apt.clientName ?? '').trim() || 'Guest';
  const serviceName = String(ctx.serviceName ?? '').trim() || 'Appointment';
  const staffName = String(ctx.staffName ?? '').trim();

  const start = toDate(apt.startTime);
  const end = toDate(apt.endTime);
  const day = dayLabel(start);
  const from = timeLabel(start);
  const to = timeLabel(end);
  const window_ = from ? (to ? `${from} – ${to}` : from) : '';
  const duration = durationLabel(minutesBetween(start, end));

  const { value: scanValue, isShortCode } = ticketScanValue(apt);
  // Short codes are matched case-insensitively at lookup, so printing them
  // uppercase is both safe and far easier to read off paper. Tokens are matched
  // exactly and must be left alone.
  const codeForScanner = isShortCode ? scanValue.toUpperCase() : scanValue;
  const codeForHumans = isShortCode ? scanValue.toUpperCase() : '';

  const checkInUrl = ticketCheckInUrl(apt, ctx.origin);
  // Whatever the guest scans has to resolve. A full URL opens their page in one
  // tap; with no origin available the bare token still identifies the visit.
  const qrPayload = checkInUrl || String(apt.checkInToken ?? '').trim() || codeForScanner;

  const qr = qrPayload ? qrSvg(qrPayload, 118) : '';
  const barcode = codeForScanner ? code128Svg(codeForScanner, 46, 2) : '';

  const addOns = (ctx.addOnNames ?? []).map((s) => String(s ?? '').trim()).filter(Boolean);
  const stations = (ctx.resourceNames ?? []).map((s) => String(s ?? '').trim()).filter(Boolean);
  const price = money(ctx.priceCents);
  const deposit = money(apt.depositAmountCents);
  const depositLine = deposit
    ? `${deposit}${apt.depositStatus ? ` · ${titleCase(apt.depositStatus)}` : ''}`
    : '';

  const bookingNote = String(apt.notes ?? '').trim();
  const serviceNote = String(apt.serviceNotes ?? '').trim();

  const amenities = (ctx.amenities ?? [])
    .map((a) => {
      const name = String(a?.name ?? '').trim();
      if (!name) return '';
      const qty = Number(a?.quantity);
      const q = Number.isFinite(qty) && qty > 1 ? ` ×${qty}` : '';
      const st = String(a?.status ?? '').trim();
      return `<li><span>${esc(name)}${esc(q)}</span>${st ? `<span class="tag">${esc(titleCase(st))}</span>` : ''}</li>`;
    })
    .filter(Boolean)
    .join('');

  const statusLabel = titleCase(apt.checkInStatus === 'arrived' ? 'checked in' : apt.status) || 'Confirmed';

  // Printed on the guest stub, which is the half that leaves the building: the
  // address is there so someone holding the stub knows where to come back to,
  // and the phone so they can call without hunting for the number.
  const contactBits = [ctx.studioPhone, ctx.studioEmail, ctx.studioAddress]
    .map((s) => String(s ?? '').trim())
    .filter(Boolean)
    .map(esc)
    .join(' · ');

  const footBits = [
    esc(studioName),
    ctx.footerNote ? esc(String(ctx.footerNote).trim()) : '',
    `Printed ${esc(fmt(new Date(), { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }))}`,
    ctx.hideBranding ? '' : 'Powered by ClarityFlow',
  ]
    .filter(Boolean)
    .join(' · ');

  return `<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(`Ticket · ${clientName}`)}</title>
<style>
  :root { --ink:#0f172a; --muted:#64748b; --soft:#94a3b8; --line:#e2e8f0; --wash:#f8fafc; --accent:#4f46e5; }
  * { box-sizing:border-box; }
  html, body { margin:0; padding:0; background:#eef2f7; color:var(--ink);
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    -webkit-print-color-adjust:exact; print-color-adjust:exact; }
  .toolbar { position:sticky; top:0; z-index:5; display:flex; gap:8px; justify-content:center;
    padding:14px; background:#0f172a; }
  .toolbar button { font:inherit; font-weight:800; font-size:12px; letter-spacing:.08em;
    text-transform:uppercase; color:#0f172a; background:#fff; border:0; border-radius:10px;
    padding:0 20px; min-height:44px; cursor:pointer; }
  .toolbar button.secondary { background:transparent; color:#fff; border:1px solid #334155; }

  .sheet { max-width:720px; margin:24px auto; }
  .ticket { background:#fff; border:2px solid var(--ink); border-radius:20px; overflow:hidden;
    box-shadow:0 14px 44px rgba(15,23,42,.10); }

  .band { display:flex; align-items:center; justify-content:space-between; gap:12px;
    background:var(--ink); color:#fff; padding:13px 22px; }
  .band .who { font-size:10px; font-weight:800; letter-spacing:.26em; text-transform:uppercase; }
  .band .st { font-size:9px; font-weight:800; letter-spacing:.2em; text-transform:uppercase;
    border:1px solid rgba(255,255,255,.45); border-radius:999px; padding:4px 11px; white-space:nowrap; }

  .body { padding:24px 26px 26px; }
  .eyebrow { font-size:9px; font-weight:800; letter-spacing:.28em; text-transform:uppercase;
    color:var(--soft); margin:0 0 6px; }
  h1 { font-size:29px; line-height:1.08; letter-spacing:-.025em; margin:0 0 4px; font-weight:800; }
  .svc { font-size:15px; font-weight:600; color:#334155; margin:0; }

  .when { display:flex; flex-wrap:wrap; align-items:baseline; gap:6px 14px;
    border:2px solid var(--ink); border-radius:14px; padding:14px 18px; margin:20px 0 4px; }
  .when .d { font-size:13px; font-weight:700; letter-spacing:.02em; color:#334155; width:100%; }
  .when .t { font-size:24px; font-weight:800; letter-spacing:-.02em; }
  .when .dur { font-size:11px; font-weight:800; letter-spacing:.16em; text-transform:uppercase;
    color:var(--muted); }

  .fields { display:grid; grid-template-columns:1fr 1fr; gap:0 26px; margin:14px 0 0; }
  .f { border-bottom:1px solid var(--line); padding:10px 0; min-width:0; }
  .k { font-size:9px; font-weight:800; letter-spacing:.2em; text-transform:uppercase; color:var(--muted); }
  .v { font-size:15px; font-weight:600; margin-top:2px; overflow-wrap:break-word; }

  h2 { font-size:10px; font-weight:800; letter-spacing:.22em; text-transform:uppercase;
    color:var(--accent); margin:22px 0 8px; }
  .pill { display:inline-block; border:1.5px solid var(--ink); border-radius:999px;
    padding:4px 11px; font-size:11px; font-weight:700; margin:0 6px 6px 0; }
  .note { background:var(--wash); border:1px solid var(--line); border-left:3px solid var(--ink);
    border-radius:10px; padding:11px 13px; font-size:13px; line-height:1.5; color:#334155;
    white-space:pre-wrap; overflow-wrap:break-word; }
  ul.amen { list-style:none; margin:0; padding:0; }
  ul.amen li { display:flex; align-items:center; justify-content:space-between; gap:10px;
    border-bottom:1px solid #f1f5f9; padding:7px 0; font-size:13px; font-weight:600; }
  .tag { font-size:9px; font-weight:800; letter-spacing:.16em; text-transform:uppercase;
    color:var(--muted); border:1px solid var(--line); border-radius:999px; padding:3px 9px;
    white-space:nowrap; }

  .code { display:flex; align-items:center; gap:16px; margin-top:10px; }
  .art { flex:0 0 auto; line-height:0; }
  .art svg { display:block; }
  .art-empty { line-height:1.2; }
  .code-txt { min-width:0; }
  .mono { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:17px;
    font-weight:700; letter-spacing:.16em; margin-top:3px; overflow-wrap:break-word; }
  .mono-big { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:22px;
    font-weight:700; letter-spacing:.14em; }
  .hint { font-size:11px; color:var(--muted); margin-top:4px; line-height:1.45; }

  /* The label needs clearance below it: with no bottom margin its descenders sit
     on the stub's dashed top border and the words read as struck through. */
  .tear { display:flex; align-items:center; gap:10px; margin:0 0 10px; padding:0 6px;
    color:var(--soft); font-size:9px; font-weight:800; letter-spacing:.22em;
    line-height:1.6; text-transform:uppercase; }
  .tear .ln { flex:1 1 auto; border-top:2px dashed #cbd5e1; }
  .stub-wrap { margin-top:18px; }

  .stub { background:#fff; border:2px dashed var(--ink); border-radius:18px; padding:20px 22px;
    display:flex; gap:20px; align-items:center; }
  .stub .left { flex:1 1 auto; min-width:0; }
  .stub .right { flex:0 0 auto; text-align:center; }
  .stub h3 { font-size:20px; letter-spacing:-.02em; margin:2px 0 2px; font-weight:800; }
  .stub .meta { font-size:12px; color:#334155; font-weight:600; }
  .stub .big-code { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
    font-size:26px; font-weight:800; letter-spacing:.2em; margin:10px 0 2px; }
  .stub .url { font-size:10px; color:var(--muted); overflow-wrap:break-word; }

  .foot { margin:14px 4px 0; font-size:10px; color:#94a3b8; text-align:center; }

  @media (max-width:560px) {
    .sheet { margin:14px 12px; }
    .body { padding:20px 18px 22px; }
    h1 { font-size:24px; }
    .fields { grid-template-columns:1fr; }
    .code { flex-direction:column; align-items:flex-start; }
    .stub { flex-direction:column; align-items:flex-start; }
    .stub .right { text-align:left; }
  }

  /* On screen the ticket can breathe. On paper it has to fit one sheet with the
     stub attached, or the guest copy lands alone on page two — so the spacing is
     compressed here rather than compromised everywhere. Type sizes and the two
     code SVGs are untouched, because shrinking those is what makes a barcode
     stop scanning. */
  @media print {
    body { background:#fff; }
    .toolbar { display:none; }
    .sheet { max-width:none; margin:0; }
    .ticket { box-shadow:none; border-radius:16px; break-inside:avoid; page-break-inside:avoid; }
    .stub { break-inside:avoid; page-break-inside:avoid; padding:15px 18px; }
    .stub-wrap { margin-top:8px; }
    .tear { margin:0 0 7px; }
    .band { background:var(--ink) !important; color:#fff !important; padding:10px 20px; }
    .body { padding:16px 20px 18px; }
    h1 { font-size:26px; }
    h2 { margin:13px 0 6px; }
    .when { padding:11px 15px; margin:13px 0 0; }
    .fields { margin-top:8px; }
    .f { padding:6px 0; }
    .note { padding:9px 12px; }
    ul.amen li { padding:4px 0; }
    .code { margin-top:6px; }
    .foot { margin-top:8px; }
    @page { margin:0.45in; }
  }
</style></head>
<body>
  <div class="toolbar">
    <button onclick="window.print()">Print ticket</button>
    <button class="secondary" onclick="window.close()">Close</button>
  </div>

  <div class="sheet">
    <div class="ticket">
      <div class="band">
        <div class="who">${esc(studioName)}</div>
        <div class="st">${esc(statusLabel)}</div>
      </div>
      <div class="body">
        <p class="eyebrow">Appointment ticket</p>
        <h1>${esc(clientName)}</h1>
        <p class="svc">${esc(serviceName)}</p>

        <div class="when">
          ${day ? `<div class="d">${esc(day)}</div>` : ''}
          ${window_ ? `<div class="t">${esc(window_)}</div>` : '<div class="t">Time to be confirmed</div>'}
          ${duration ? `<div class="dur">${esc(duration)}</div>` : ''}
        </div>

        <div class="fields">
          ${field('Provider', staffName)}
          ${field(stations.length > 1 ? 'Stations' : 'Station', stations.join(' · '))}
          ${field('Service total', price)}
          ${field('Deposit', depositLine)}
          ${field('Contact', ctx.clientPhone)}
          ${field('Confirmation', codeForHumans)}
        </div>

        ${addOns.length ? `<h2>Add-ons</h2><div>${pills(addOns)}</div>` : ''}
        ${bookingNote ? `<h2>Client request</h2><p class="note">${esc(bookingNote)}</p>` : ''}
        ${serviceNote ? `<h2>Service note</h2><p class="note">${esc(serviceNote)}</p>` : ''}
        ${amenities ? `<h2>Lounge orders</h2><ul class="amen">${amenities}</ul>` : ''}

        <h2>Scan to pull this ticket up</h2>
        ${codeBlock(
          barcode,
          codeForHumans,
          'Studio scanner',
          'Scan with the desk scanner to open this appointment, or type the code into the planner search.'
        )}
      </div>
    </div>

    <div class="stub-wrap">
      <div class="tear"><span class="ln"></span> Tear here · guest copy <span class="ln"></span></div>
      <div class="stub">
        <div class="left">
          <p class="eyebrow">${esc(studioName)}</p>
          <h3>${esc(clientName)}</h3>
          <div class="meta">${esc([serviceName, day, window_].filter(Boolean).join(' · '))}</div>
          ${codeForHumans ? `<div class="big-code">${esc(codeForHumans)}</div>` : ''}
          <div class="url">${
            checkInUrl
              ? `Scan the code to follow your visit, order from the lounge, and see what else we offer.<br />${esc(checkInUrl)}`
              : 'Keep this stub — the front desk can look your visit up with this code.'
          }</div>
          ${contactBits ? `<div class="url" style="margin-top:6px;">${contactBits}</div>` : ''}
        </div>
        ${qr ? `<div class="right"><div class="art">${qr}</div></div>` : ''}
      </div>
    </div>

    <div class="foot">${footBits}</div>
  </div>
  <script>try{window.focus();}catch(e){}</script>
</body></html>`;
}

/**
 * Builds the ticket and opens it in a new tab with the print dialog ready.
 *
 * Returns false when a popup blocker stopped the window from opening, which is
 * common and silent — the caller should surface a toast telling the owner to
 * allow popups, otherwise pressing Print appears to do nothing at all.
 */
export function printAppointmentTicket(apt: TicketAppointment, ctx: TicketContext = {}): boolean {
  return openPrintable(appointmentTicketHtml(apt, ctx));
}
