
'use client';

import React from 'react';
import { format } from 'date-fns';
import { Separator } from '@/components/ui/separator';
import { type Service, type Client, type Appointment } from '@/lib/data';

export interface TicketData {
  business: {
    name: string;
    phone: string;
  };
  client: Client;
  appointment: Appointment;
  service: Service;
}

interface PrintTicketProps {
  data: TicketData;
}

export const PrintTicket: React.FC<PrintTicketProps> = ({ data }) => {
  const { client, service, appointment } = data;

  return (
    <div className="p-4 bg-white text-black font-sans text-sm max-w-md mx-auto">
       <style>{`
        @media print {
          body {
            background-color: #fff;
          }
          .print-content {
            box-shadow: none !important;
            border: none !important;
            margin: 0 !important;
            padding: 0 !important;
            max-width: 100% !important;
            width: 100% !important;
            border-radius: 0 !important;
          }
          .print-content > *:not(#ticket-area) {
            display: none !important;
          }
          #ticket-area {
            display: block !important;
          }
        }
      `}</style>
      <div className="text-center space-y-1 mb-6">
        <h1 className="text-2xl font-bold">{service.name}</h1>
        <p className="text-base font-medium">{client.name}</p>
        <p className="text-gray-600">{format(appointment.startTime, 'MMM d, yyyy h:mm a')}</p>
      </div>

      <Separator className="my-4 border-dashed border-black" />

      <div className="space-y-4">
        <div>
            <h2 className="text-lg font-semibold mb-2">Service Formula</h2>
            <div className="space-y-2 pl-4">
                {(service.products && service.products.length > 0) ? (
                    service.products.map((item, index) => (
                    <div key={index} className="flex justify-between">
                        <p>{item.name}</p>
                        <p>{item.quantityUsed}{item.unit}</p>
                    </div>
                    ))
                ) : (
                    <p className="text-gray-500">No products in formula.</p>
                )}
            </div>
        </div>

        {client.notes && (
             <div>
                <h2 className="text-lg font-semibold mb-2">Client Notes</h2>
                <div className="p-3 bg-gray-100 rounded-md">
                    <p className="text-gray-700">{client.notes}</p>
                </div>
            </div>
        )}

      </div>
       <div className="text-center mt-8">
        <p className="text-gray-500 text-xs">Generated by ClarityFlow</p>
      </div>
    </div>
  );
};
